// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXLebllipLEhoMDy26RlKCZcuByWWRD3k',
    appId: '1:944733144482:web:51834549a5b5a71ed5defb',
    messagingSenderId: '944733144482',
    projectId: 'muziklokal-6a50b',
    authDomain: 'muziklokal-6a50b.firebaseapp.com',
    storageBucket: 'muziklokal-6a50b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA0vZ8fuMHCtpIpVLpYMKyLa3np0kEw7c',
    appId: '1:944733144482:android:42169458c8dbaab7d5defb',
    messagingSenderId: '944733144482',
    projectId: 'muziklokal-6a50b',
    storageBucket: 'muziklokal-6a50b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKUibwu1W8IZVzTJRMGIjBAS4K4Imh-QU',
    appId: '1:944733144482:ios:9b9dcabf6a69cb1dd5defb',
    messagingSenderId: '944733144482',
    projectId: 'muziklokal-6a50b',
    storageBucket: 'muziklokal-6a50b.appspot.com',
    iosBundleId: 'com.example.muzikLocal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKUibwu1W8IZVzTJRMGIjBAS4K4Imh-QU',
    appId: '1:944733144482:ios:9b9dcabf6a69cb1dd5defb',
    messagingSenderId: '944733144482',
    projectId: 'muziklokal-6a50b',
    storageBucket: 'muziklokal-6a50b.appspot.com',
    iosBundleId: 'com.example.muzikLocal',
  );
}
